version: "3"
services:
  todosDB:
    image: postgres:15.3
    container_name: todos-db
    ports:
      - 5440:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pga1123ada*
    volumes:
      - ./postgres:/var/lib/postgresql/data
